[package]
name = "touchp"
description = "Create file(s) recursively like `mkdir -p`"
version = "0.1.0"
authors = ["Guntur Poetra"]
edition = "2021"
repository = "https://github.com/iguntur/touchp"
license = "MIT"
categories = ["command-line-utilities", "development-tools", "filesystem"]
